### Exercícios - Capítulo 4

In [1]:
import numpy as np

1. Crie dois NumPy Arrays unidimensionais de tamanho 8: um formado apenas por 1’s e outro formado por números aleatórios entre 0 e 9. Some estes dois NumPy Arrays e guarde o resultado dentro de um terceiro NumPy Array. Por fim, faça o seguinte:

    a. Se a soma de todos os elementos do Array resultante for >= 40, remodele este NumPy Array para se tornar uma matriz com mais linhas do que colunas. Senão, remodele para que se torne uma matriz com mais colunas do que linhas. 

In [2]:
arr1 = np.ones(8) # array de 1's
arr2 = np.random.randint(0,10,8) # array de núm aleatórios

arr3 = arr1+arr2

# Mostrar os arrays criados
print(arr1, arr2, arr3)

if arr3.sum() >= 40:
    arr4 = arr3.reshape(4,2)
else:
    arr4 = arr3.reshape(2,4)

print('Soma: ', arr3.sum())
print('Array remodelado: ', arr4)

[1. 1. 1. 1. 1. 1. 1. 1.] [2 4 1 1 5 6 1 5] [3. 5. 2. 2. 6. 7. 2. 6.]
Soma:  33.0
Array remodelado:  [[3. 5. 2. 2.]
 [6. 7. 2. 6.]]


2. Crie dois NumPy Arrays unidimensionais: um de números pares de 0 à 51 e outro também de números pares de 100 até 50. Em seguida, os concatene e mostre os resultados ordenados 

In [3]:
arr1 = np.arange(0, 51, 2)
arr2 = np.arange(100, 50, -2)

# Concatenar e ordenar arrays
arr3 = np.sort(np.concatenate((arr1, arr2)))
print(arr3)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


3. Mini Campo Minado

    a) Crie um NumPy Array 2x2 formado apenas por 0’s

    b) Em seguida, adicione um número 1 em uma posição aleatória desta matriz;
    
    c) Faça uma entrada de dados para solicitar o usuário que faça uma jogada (selecione uma posição da matriz)

    I. Se ele selecionar todas as posições em que o número 1 não se encontra, mostre a mensagem “Congratulations! You beat the game! :)”
        
    II. Senão, se dentro das 3 primeiras jogadas ele achar o número 1, mostre a mensagem “Game Over! :( Try Again!”

In [4]:
campo = np.zeros([2,2]) # criar campo minado de 0's

campo[tuple(np.random.randint(0, 2, 2))] = 1 # adicionar 1 em posição aleatória

print('Campo Minado!')
while campo.sum()!=7:
    print('\nFaça uma jogada!')
    x = int(input('Qual a posição x?'))
    y = int(input('Qual a posição y?'))

    if (x not in range(0,2))or(y not in range(0,2)):
        print('Posição inválida! Entre com valores 0 ou 1 para x e y!')
    elif campo[x,y]==1:
        print('Game Over! :( Try Again!')
        break
    else:
        campo[x,y] = 2
        print('Você está seguro!')      

if campo.sum()==7:
    print('Congratulations! You beat the game! :)')

Campo Minado!

Faça uma jogada!
Você está seguro!

Faça uma jogada!
Game Over! :( Try Again!


4. Crie uma matriz de tamanho qualquer. Extraia seu número de linhas e colunas, multiplique-os, e diga se esta matriz poderia se tornar um vetor unidimensional com número par ou ímpar de elementos

In [7]:
mtz = np.zeros(tuple(np.random.randint(1, 11, 2))) # matriz de 0's de tamanho qualquer

if (mtz.shape[0]*mtz.shape[1])%2 == 0:
    print('Essa matriz poderia se tornar um vetor unidimensional com número par de elementos.')
else:
    print('Essa matriz poderia se tornar um vetor unidimensional com número ímpar de elementos.')

print('Matriz: ', mtz)

Essa matriz poderia se tornar um vetor unidimensional com número ímpar de elementos.
Matriz:  [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


5. Crie uma matriz de tamanho 4x4 formada por números aleatórios inteiros entre 1 e 50 (use seed = 10 antes)

    a) Mostre o resultado da média de cada linha e cada coluna da matriz gerada

    b) Apresente o maior valor das médias das linhas e também das colunas
    
    c) Mostre a quantidade de aparições de cada um dos números gerados na matriz. Em seguida, mostre apenas os números que aparecem 2 vezes

In [6]:
np.random.seed(10)
mtz = np.random.randint(1, 50, [4, 4])

print('Matriz: ', mtz, '\n')

media_col = mtz.mean(axis=0)
media_li = mtz.mean(axis=1)

for i in range(4):
    print('A média da linha',(i+1),'é', media_li[i])
    print('A média da coluna',(i+1),'é', media_col[i])

print('\nO maior valor das médias das linhas é',media_li.max(),'e das colunas é', media_col.max(),'\n')

aparicoes = np.unique(mtz, return_counts=True)

for i in range(aparicoes[0].size):
    print('O número',aparicoes[0][i],'aparece',aparicoes[1][i],'vezes')

duas_vezes = aparicoes[0][aparicoes[1]==2]

print('\nOs números que aparecem duas vezes são:')
for i in duas_vezes:
    print(i)

Matriz:  [[10 37 16  1]
 [29 26 30 49]
 [30  9 10  1]
 [43 41 37 17]] 

A média da linha 1 é 16.0
A média da coluna 1 é 28.0
A média da linha 2 é 33.5
A média da coluna 2 é 28.25
A média da linha 3 é 12.5
A média da coluna 3 é 23.25
A média da linha 4 é 34.5
A média da coluna 4 é 17.0

O maior valor das médias das linhas é 34.5 e das colunas é 28.25 

O número 1 aparece 2 vezes
O número 9 aparece 1 vezes
O número 10 aparece 2 vezes
O número 16 aparece 1 vezes
O número 17 aparece 1 vezes
O número 26 aparece 1 vezes
O número 29 aparece 1 vezes
O número 30 aparece 2 vezes
O número 37 aparece 2 vezes
O número 41 aparece 1 vezes
O número 43 aparece 1 vezes
O número 49 aparece 1 vezes

Os números que aparecem duas vezes são:
1
10
30
37
