## Introdução ao NumPy

Iniciando com o NumPy

In [19]:
import numpy as np

# NumPy Array Unidimensional
arr = np.array([1, 2, 3])

# NumPy Array Bidimensional
mtz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr)
print(mtz)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Criando NUmPy Arrays com mais facilidade

In [20]:
# Estrututando rapidamente uma matriz de 1's
mtz = np.ones([5,5])
print(mtz)

# Arange
mtz = np.arange(10)
print(mtz)

arr = np.arange(10, 30, 2)
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[10 12 14 16 18 20 22 24 26 28]


Operações com NumPy Arrays

In [21]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

print(arr1.min(), arr1.max())
print(arr1.argmin(), arr2.argmax())

print(arr1.mean(), arr1.sum())

# Operações entre dois ou mais arrays
arr3 = arr1+arr2
print(arr3)

# Concatenando NumPy Arrays
arr4 = np.concatenate([arr1, arr2])
print(arr4)

1 4
0 3
2.5 10
[ 6  8 10 12]
[1 2 3 4 5 6 7 8]


Reshape de NumPy Arrays

In [22]:
mtz = np.arange(9).reshape(3,3)
print(mtz)

print(mtz.size)
print(mtz.shape)
print(mtz.ndim)

# Operações nas linhas e colunas da matriz
print(mtz.sum(axis=0)[0])
print(mtz.sum(axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
9
(3, 3)
2
9
[ 3 12 21]


Broadcasting

In [23]:
print(mtz/2)

[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]


Elementos Aleatórios e Únicos

In [29]:
# Gerando números aletórios
np.random.seed(10)
arr = np.random.randint(20, 50, [5, 5])
print(arr)

# Extraindo elementos únicos com unique
print(np.unique(arr, return_counts=True))


[[29 49 24 35 20]
 [37 47 48 45 49]
 [36 49 37 46 28]
 [29 20 30 28 42]
 [24 39 36 24 35]]
(array([20, 24, 28, 29, 30, 35, 36, 37, 39, 42, 45, 46, 47, 48, 49],
      dtype=int32), array([2, 3, 2, 2, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 3]))
